/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicLibrary;

import java.awt.BorderLayout;
import java.awt.Color;
import myutil.Colour;

/**
 *
 * @author nbp184
 */
public class CardPopupDialog extends javax.swing.JDialog {

    public final int row;
    
    /**
     * Creates new form CardPopupDialog
     */
    public CardPopupDialog(java.awt.Frame parent, Card c, int row, java.awt.Point p) {
        super(parent, false);
        initComponents();
        lblName.setText(c.name);
        ManaPanel mp = new ManaPanel(c.manaCost);
        pnlManaHolder.setLayout(new BorderLayout());
        pnlManaHolder.add(mp, BorderLayout.LINE_END);
        lblType.setText(c.getAllTypeString());
        txtText.setText(c.text);
        if(c.loyalty != null) {
            lblLPT.setText(c.loyalty);
        } else if(c.power != null) {
            lblLPT.setText(c.power +"/" +c.toughness);
        } else {
            lblLPT.setText(" ");
        }
        Color bg = Colour.LightGray;
        if(c.hasSuperType("Basic")) {
            switch(c.name) {
                case "Plains":
                    bg = Color.white;
                    break;
                case "Island":
                    bg = Colour.DodgerBlue;
                    break;
                case "Swamp":
                    bg = Colour.RebeccaPurple;
                    break;
                case "Mountain":
                    bg = Colour.FireBrick;
                    break;
                case "Forest":
                    bg = Colour.SeaGreen;
                    break;
            }
        } else if(c.hasType("Land")) {
            bg = Colour.BurlyWood;
        } else if(!c.hasType("Artifact")) {
            bg = Colour.Gold;
            switch(c.getColours()) {
                case 1:
                    bg = Color.white;
                    break;
                case 2:
                    bg = Colour.DodgerBlue;
                    break;
                case 4:
                    bg = Colour.RebeccaPurple;
                    break;
                case 8:
                    bg = Colour.FireBrick;
                    break;
                case 16:
                    bg = Colour.SeaGreen;
                    break;
            }
        }
        if(bg != null) {
            this.getContentPane().setBackground(bg);
            mp.setBackground(bg);
        }
        setLocation(p);
        this.row = row;
        setVisible(true);
    }
    
    public void move(java.awt.Point p) {
        setLocation(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        pnlManaHolder = new javax.swing.JPanel();
        lblType = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        lblLPT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblName.setText("jLabel1");

        javax.swing.GroupLayout pnlManaHolderLayout = new javax.swing.GroupLayout(pnlManaHolder);
        pnlManaHolder.setLayout(pnlManaHolderLayout);
        pnlManaHolderLayout.setHorizontalGroup(
            pnlManaHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlManaHolderLayout.setVerticalGroup(
            pnlManaHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        lblType.setText("jLabel1");

        txtText.setEditable(false);
        txtText.setColumns(20);
        txtText.setLineWrap(true);
        txtText.setRows(5);
        txtText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtText);

        lblLPT.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(pnlManaHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLPT)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManaHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLPT)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLPT;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel pnlManaHolder;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
