/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicLibrary;

import java.util.ArrayList;

/**
 *
 * @author nbp184
 */
public class DeckListDialog extends javax.swing.JDialog {
    
    public static void showDialog(java.awt.Frame parent, Deck d, boolean sortBySet) {
        DeckListDialog dld = new DeckListDialog(parent, d, false, sortBySet);
        dld.setVisible(true);
    }
    
    public static void showNeedDialog(java.awt.Frame parent, Deck d, boolean sortBySet) {
        DeckListDialog dld = new DeckListDialog(parent, d, true, sortBySet);
        dld.setVisible(true);
    }
    
    private int mode; //x, no x, nothing
    private String original;
    
    /**
     * Creates new form DeckListDialog
     */
    private DeckListDialog(java.awt.Frame parent, Deck d, boolean needOnly, boolean sortBySet) {
        super(parent, true);
        initComponents();
        setTitle(d +" Deck List");
        original = "";
        if(sortBySet) {
            ArrayList<String> setNames = new ArrayList<>();
            Deck.DeckCard[][] sorted = new Deck.DeckCard[500][d.size()];
            int count = 0;
            int[] counts = new int[500];
            int index;
            for(Deck.DeckCard dc : d) {
                if(dc.count > dc.card.count || !needOnly) {
                    if(dc.card.hasSuperType("Basic")) {
                        index = setNames.indexOf("Basic Land");
                        if(index < 0) {
                            setNames.add("Basic Land");
                            index = count++;
                        }
                        sorted[index][counts[index]++] = dc;
                    } else if(dc.card.sets == null || dc.card.sets.length == 0) {
                        index = setNames.indexOf("No Set");
                        if(index < 0) {
                            setNames.add("No Set");
                            index = count++;
                        }
                        sorted[index][counts[index]++] = dc;
                    } else {
                        for(String s : dc.card.sets) {
                            index = setNames.indexOf(s);
                            if(index < 0) {
                                setNames.add(s);
                                index = count++;
                            }
                            sorted[index][counts[index]++] = dc;
                        }
                    }
                }
            }
            for(int i = 0; i < count; i++) {
                if(i > 0) {
                    original += "\n\n";
                }
                original += setNames.get(i) +":";
                for(int j = 0; j < counts[i]; j++) {
                    original += "\n    ";
                    if(needOnly && sorted[i][j].count > sorted[i][j].card.count) {
                        original += (sorted[i][j].count - sorted[i][j].card.count) +"x " +sorted[i][j].card.name;
                    } else if(!needOnly) {
                        original += sorted[i][j].count +"x " +sorted[i][j].card.name;
                    }
                    if(!sorted[i][j].card.hasSuperType("Basic") && sorted[i][j].card.sets != null && sorted[i][j].card.sets.length > 1) {
                        original += " (M)";
                    }
                }
            }
        } else {
            for(Deck.DeckCard dc : d) {
                if(needOnly && dc.count > dc.card.count) {
                    if(!original.isEmpty()) {
                        original += "\n";
                    }
                    original += (dc.count - dc.card.count) +"x " +dc.card.name;
                } else if(!needOnly) {
                    if(!original.isEmpty()) {
                        original += "\n";
                    }
                    original += dc.count +"x " +dc.card.name;
                }
            }
        }
        mode = 0;
        txtList.setText(original);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFormat = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtList = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        rbX = new javax.swing.JRadioButton();
        rbNoX = new javax.swing.JRadioButton();
        rbNothing = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtList.setEditable(false);
        txtList.setColumns(20);
        txtList.setRows(5);
        jScrollPane1.setViewportView(txtList);

        jLabel1.setText("Format:");

        bgFormat.add(rbX);
        rbX.setSelected(true);
        rbX.setText("(count)x (name)");
        rbX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbXActionPerformed(evt);
            }
        });

        bgFormat.add(rbNoX);
        rbNoX.setText("(count) (name)");
        rbNoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoXActionPerformed(evt);
            }
        });

        bgFormat.add(rbNothing);
        rbNothing.setText("(name)");
        rbNothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNothingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbNoX))
                            .addComponent(rbNothing))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbX)
                    .addComponent(rbNoX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbNothing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbXActionPerformed
        if(mode != 0) {
            mode = 0;
            txtList.setText(original);
        }
    }//GEN-LAST:event_rbXActionPerformed

    private void rbNoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoXActionPerformed
        if(mode != 1) {
            mode = 1;
            String t = original.replaceAll("(?<=\\d+)x", "");
            txtList.setText(t);
        }
    }//GEN-LAST:event_rbNoXActionPerformed

    private void rbNothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNothingActionPerformed
        if(mode != 2) {
            mode = 2;
            String t = original.replaceAll("\\d+x ", "");
            txtList.setText(t);
        }
    }//GEN-LAST:event_rbNothingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFormat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbNoX;
    private javax.swing.JRadioButton rbNothing;
    private javax.swing.JRadioButton rbX;
    private javax.swing.JTextArea txtList;
    // End of variables declaration//GEN-END:variables

}
