/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicLibrary;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author nbp184
 */
public class DriveDialog extends javax.swing.JDialog {

    public static void showUploadDialog(java.awt.Frame parent, File cardFile, File deckFile) {
        DriveDialog dd = new DriveDialog(parent);
        dd.cardFile = cardFile;
        dd.deckFile = deckFile;
        dd.lblMessage.setText("Uploading");
        dd.mode = 1;
        dd.setVisible(true);
        dd.dispose();
    }
    
    public static void showDownloadDialog(java.awt.Frame parent, File cardFile, File deckFile) {
        DriveDialog dd = new DriveDialog(parent);
        dd.cardFile = cardFile;
        dd.deckFile = deckFile;
        dd.lblMessage.setText("Downloading");
        dd.mode = 2;
        dd.setVisible(true);
        dd.dispose();
    }
    
    public static Library.Differences showDifferenceDialog(java.awt.Frame parent, File cardFile, File deckFile) {
        DriveDialog dd = new DriveDialog(parent);
        dd.cardFile = cardFile;
        dd.deckFile = deckFile;
        dd.lblMessage.setText("Computing Differences");
        dd.mode = 3;
        dd.setVisible(true);
        Library.Differences rv = dd.differences;
        dd.dispose();
        return rv;
    }
    
    private File cardFile;
    private File deckFile;
    private int mode;//1 - upload, 2 - download, 3 - diff
    private Library.Differences differences;
    
    /**
     * Creates new form DriveDialog
     */
    private DriveDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblMessage.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            GoogleDriveInterface gdi = new GoogleDriveInterface();
            switch(mode) {
                case 1:
                    gdi.uploadFiles(cardFile, deckFile);
                    break;
                case 2:
                    gdi.downloadFiles(cardFile, deckFile);
                    break;
                case 3:
                    gdi.downloadFiles(cardFile, deckFile);
                    differences = Library.getDifferences(cardFile, deckFile);
                    break;
            }
            setVisible(false);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
