/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicLibrary;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author nbp184
 */
public class MainFrame extends javax.swing.JFrame {

    public static final String filename = "library.txt";
    private static MainFrame instance = null;
    
    public static MainFrame getInstance() {
        return instance;
    }
    
    private LibraryPanel pnlLib;
    
    /**
     * Creates new form MainFrame
     */
    private MainFrame() {
        initComponents();
        File f = new File(filename);
        if(f.exists()) {
            try {
                Library.makeLibrary(f);
            } catch (IOException ex) {
                System.out.println("Library creation failed");
                System.out.println(ex.getMessage());
                ex.printStackTrace(System.out);
            }
        }
        pnlLib = new SimpleLibraryPanel();
        tabMain.add("Library", pnlLib);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        mbMain = new javax.swing.JMenuBar();
        mCard = new javax.swing.JMenu();
        miNewCard = new javax.swing.JMenuItem();
        mDeck = new javax.swing.JMenu();
        miNewDeck = new javax.swing.JMenuItem();
        miAddCardToDeck = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magic Library");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mCard.setText("Card");

        miNewCard.setText("Add New");
        miNewCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewCardActionPerformed(evt);
            }
        });
        mCard.add(miNewCard);

        mbMain.add(mCard);

        mDeck.setText("Deck");

        miNewDeck.setText("New Deck");
        miNewDeck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewDeckActionPerformed(evt);
            }
        });
        mDeck.add(miNewDeck);

        miAddCardToDeck.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        miAddCardToDeck.setText("Add Card to Deck");
        miAddCardToDeck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddCardToDeckActionPerformed(evt);
            }
        });
        mDeck.add(miAddCardToDeck);

        mbMain.add(mDeck);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        File f = new File(filename);
        try {
            Library.getInstance().save();
        } catch (IOException ex) {
            System.out.println("Library save failed");
            System.out.println(ex.getMessage());
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_formWindowClosing

    private void miNewCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewCardActionPerformed
        Card c = CardDialog.showNewDialog(this, true);
        if(c != null) {
            Library.getInstance().addCard(c);
            pnlLib.fireLibraryChanged();
        }
    }//GEN-LAST:event_miNewCardActionPerformed

    private void miNewDeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewDeckActionPerformed
        String value = "";
        while(value.isEmpty()) {
            value = (String)JOptionPane.showInputDialog(this, "What is the new deck's name?", "New Deck", JOptionPane.QUESTION_MESSAGE, null, null, "");
            if(value == null) {
                break;
            }
            value = value.trim();
            if(value.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Name cannot be blank.", "New Deck", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(value != null) {
            Library.getInstance().addDeck(value);
        }
    }//GEN-LAST:event_miNewDeckActionPerformed

    private void miAddCardToDeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddCardToDeckActionPerformed
        //todo: 
    }//GEN-LAST:event_miAddCardToDeckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                instance = new MainFrame();
                instance.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mCard;
    private javax.swing.JMenu mDeck;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miAddCardToDeck;
    private javax.swing.JMenuItem miNewCard;
    private javax.swing.JMenuItem miNewDeck;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables

}
