/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicLibrary;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author nbp184
 */
public class MainFrame extends javax.swing.JFrame implements LibraryPanel.ChangePanelListener {

    public static final String cardFile = "library.txt";
    public static final String deckFile = "boxes.txt";
    private static MainFrame instance = null;
    
    public static MainFrame getInstance() {
        return instance;
    }
    
    private int current;
    private File fc;
    private File fd;
    
    /**
     * Creates new form MainFrame
     */
    private MainFrame() {
        initComponents();
        fc = new File(cardFile);
        fd = new File(deckFile);
        if(fc.exists() && fd.exists()) {
            try {
                Library.makeLibrary(fc, fd);
            } catch (IOException ex) {
                System.out.println("Library creation failed");
                System.out.println(ex.getMessage());
                ex.printStackTrace(System.out);
            }
        }
        pnlMain.setLayout(new CardLayout());
        LibraryPanel pnlLib = new SimpleLibraryPanel();
        pnlLib.addChangePanelListener(this);
        pnlMain.add(pnlLib, "Simple");
        pnlLib = new AdvancedLibraryPanel();
        pnlLib.addChangePanelListener(this);
        pnlMain.add(pnlLib, "Advanced");
        pnlMain.add(new DeckPanel(), "Deck");
        current = 0;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        mbMain = new javax.swing.JMenuBar();
        mCard = new javax.swing.JMenu();
        miNewCard = new javax.swing.JMenuItem();
        miJSONCard = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miNewDeck = new javax.swing.JMenuItem();
        miDeckMode = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magic Library");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        mCard.setText("Card");

        miNewCard.setText("Add New");
        miNewCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewCardActionPerformed(evt);
            }
        });
        mCard.add(miNewCard);

        miJSONCard.setText("Add from JSON");
        miJSONCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJSONCardActionPerformed(evt);
            }
        });
        mCard.add(miJSONCard);

        mbMain.add(mCard);

        jMenu1.setText("Decks");

        miNewDeck.setText("New Deck");
        miNewDeck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewDeckActionPerformed(evt);
            }
        });
        jMenu1.add(miNewDeck);

        miDeckMode.setText("Deck Mode");
        miDeckMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeckModeActionPerformed(evt);
            }
        });
        jMenu1.add(miDeckMode);

        mbMain.add(jMenu1);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Library.getInstance().save(fc, fd);
        } catch (IOException ex) {
            System.out.println("Library save failed");
            System.out.println(ex.getMessage());
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_formWindowClosing

    private void miNewCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewCardActionPerformed
        Card c = CardDialog.showNewDialog(this, true);
        if(c != null) {
            if(Library.getInstance().addCard(c)) {
                ((LibraryPanel)pnlMain.getComponent(current)).fireLibraryChanged();
                ((DeckPanel)pnlMain.getComponent(2)).fireLibraryChanged(true);
            } else {
                int result = JOptionPane.showConfirmDialog(this, "You already have " +c.name +" in your library, edit now?", "Add to Library", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                if(result == JOptionPane.YES_OPTION) {
                    if(CardDialog.showEditDialog(MainFrame.getInstance(), true, Library.getInstance().getCardByName(c.name))) {
                        ((LibraryPanel)pnlMain.getComponent(current)).fireLibraryChanged();
                        ((DeckPanel)pnlMain.getComponent(2)).fireLibraryChanged(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_miNewCardActionPerformed

    private void miJSONCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJSONCardActionPerformed
        try {
            if(JSONCardDialog.showDialog(this)) {
                ((LibraryPanel)pnlMain.getComponent(current)).fireLibraryChanged();
                ((DeckPanel)pnlMain.getComponent(2)).fireLibraryChanged(true);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Couldn't find JSON file.");
            System.out.println(ex.getMessage());
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_miJSONCardActionPerformed

    private void miDeckModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeckModeActionPerformed
        CardLayout lo = (CardLayout)pnlMain.getLayout();
        if(miDeckMode.isSelected()) {
            lo.show(pnlMain, "Deck");
        } else if(current == 0) {
            lo.show(pnlMain, "Simple");
        } else {
            lo.show(pnlMain, "Advanced");
        }
    }//GEN-LAST:event_miDeckModeActionPerformed

    private void miNewDeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewDeckActionPerformed
        String result = JOptionPane.showInputDialog(this, "Enter new deck name", "New Deck", JOptionPane.QUESTION_MESSAGE);
        if(result != null) {
            Deck d = new Deck(result);
            if(Library.getInstance().addDeck(d)) {
                ((DeckPanel)pnlMain.getComponent(2)).fireLibraryChanged(false);
            } else {
                JOptionPane.showMessageDialog(this, "You already have a deck called " +result +".", "New Deck", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_miNewDeckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                instance = new MainFrame();
                instance.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu mCard;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JCheckBoxMenuItem miDeckMode;
    private javax.swing.JMenuItem miJSONCard;
    private javax.swing.JMenuItem miNewCard;
    private javax.swing.JMenuItem miNewDeck;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changePanel(String newPanelName) {
        switch(newPanelName) {
            case "Simple":
                current = 0;
                Library.getInstance().clearSearch();
                break;
            case "Advanced":
                current = 1;
                Library.getInstance().doSearch(""+Library.NULL);
                break;
        }
        CardLayout lo = (CardLayout)pnlMain.getLayout();
        lo.show(pnlMain, newPanelName);
    }

}
