/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicLibrary;

/**
 *
 * @author nbp184
 */
public class MoneyPanel extends javax.swing.JPanel {

    /**
     * Creates new form MoneyPanel
     */
    public MoneyPanel() {
        initComponents();
        txtAmount.setText("0.00");
    }
    
    public MoneyPanel(float amount) {
        initComponents();
        setAmount(amount);
    }
    
    public void setAmount(float amount) {
        String s = ""+amount;
        if(!s.contains(".")) {
            s += ".00";
        } else {
            int i = s.indexOf(".");
            while(s.length() - i <= 2) {
                s += "0";
            }
        }
        txtAmount.setText(s);
    }
    
    public boolean isValidAmount() {
        try {
            Float.parseFloat(txtAmount.getText());
            return true;
        } catch(Exception ex) {
            return false;
        }
    }
    
    public float getAmount() {
        String s = txtAmount.getText();
        int i = s.indexOf(".");
        if(i > 0 && s.length() - i > 2) {

        }
        return Float.parseFloat(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
